### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by rodriguez-facundo** [openworm/org.geppetto.frontend.jupyter#61]
### branch feature/extensible_routes

Hi @filippometacell,
running `jupyter nbextension install --py --symlink  --sys-prefix jupyter_geppetto` procudes the following error during the installation process:

```
Installing collected packages: jupyter-geppetto
  Running setup.py develop for jupyter-geppetto
Successfully installed jupyter-geppetto
Traceback (most recent call last):
  File "/Users/snakes/miniconda3/envs/nwb/bin/jupyter-nbextension", line 10, in <module>
    sys.exit(main())
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/notebook/nbextensions.py", line 677, in install_extensions
    raise ValueError("Only one nbextension allowed at a time. "
ValueError: Only one nbextension allowed at a time. Call multiple times to install multiple extensions.
Please specify one nbextension/package at a time
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Traceback (most recent call last):
  File "/Users/snakes/miniconda3/envs/nwb/bin/jupyter-serverextension", line 10, in <module>
    sys.exit(main())
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/notebook/serverextensions.py", line 294, in start
    super(ServerExtensionApp, self).start()
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/notebook/serverextensions.py", line 211, in start
    self.toggle_server_extension_python(arg)
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/notebook/serverextensions.py", line 200, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/notebook/serverextensions.py", line 328, in _get_server_extension_metadata
    m = import_item(module)
  File "/Users/snakes/miniconda3/envs/nwb/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/Users/snakes/Desktop/nwb-explorer/utilities/dependencies/org.geppetto.frontend.jupyter/jupyter_geppetto/__init__.py", line 143, in <module>
    RouteManager.add_web_client(PathService.get_webapp_directory())
  File "/Users/snakes/Desktop/nwb-explorer/utilities/dependencies/org.geppetto.frontend.jupyter/jupyter_geppetto/service.py", line 12, in get_webapp_directory
    cls.webapp_directory = os.path.dirname(glob.glob('*/' + settings.geppetto_webapp_file)[0])
```

**Comment by filippometacell** [comment]
Hi Facu, was that on a new conda environment? Have you also tried with the install.py script? Let's look at that together

**Comment by rodriguez-facundo** [comment]
Hi, yes it was a new env. Steps to reproduce:

- `rm -rf ~/.jupyter`
- `conda create nwb python=3`
- `. activate nwb`
- `git clone -b git@github.com:tarelli/nwb-explorer.git nwb`
- `cd nwb/utilities`
- `python install.py`
